// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneToManyWebAPI.Models;

#nullable disable

namespace OneToManyWebAPI.Migrations
{
    [DbContext(typeof(MenuForAPIContext))]
    [Migration("20230508071551_Sample")]
    partial class Sample
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneToManyWebAPI.Models.MenuForAPI", b =>
                {
                    b.Property<int?>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ItemID"));

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemPrice")
                        .HasColumnType("int");

                    b.Property<int?>("MtypeTypeID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("MtypeTypeID");

                    b.ToTable("MenuFors");
                });

            modelBuilder.Entity("OneToManyWebAPI.Models.MenuTypeAPI", b =>
                {
                    b.Property<int?>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TypeID"));

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeID");

                    b.ToTable("MenuTypes");
                });

            modelBuilder.Entity("OneToManyWebAPI.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("userInfos");
                });

            modelBuilder.Entity("OneToManyWebAPI.Models.MenuForAPI", b =>
                {
                    b.HasOne("OneToManyWebAPI.Models.MenuTypeAPI", "Mtype")
                        .WithMany("Menus")
                        .HasForeignKey("MtypeTypeID");

                    b.Navigation("Mtype");
                });

            modelBuilder.Entity("OneToManyWebAPI.Models.MenuTypeAPI", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
