<?xml version="1.0" encoding="utf-8"?><Database Name="CIET" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GL7RKG7\SQLEXPRESS;Initial Catalog=CIET;Integrated Security=True" SettingsObjectName="WindowsFormsApp_Linq_to_sql.Properties.Settings" SettingsPropertyName="CIETConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clg_Depts" Member="Clg_Depts">
    <Type Name="Clg_Dept">
      <Column Name="Rollno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Stdname" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Phoneno" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MailID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Stdaddress" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Bloodgrp" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeptID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>