#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Linq_to_sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CIET")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClg_Dept(Clg_Dept instance);
    partial void UpdateClg_Dept(Clg_Dept instance);
    partial void DeleteClg_Dept(Clg_Dept instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp_Linq_to_sql.Properties.Settings.Default.CIETConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clg_Dept> Clg_Depts
		{
			get
			{
				return this.GetTable<Clg_Dept>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clg_Depts")]
	public partial class Clg_Dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Rollno;
		
		private string _Stdname;
		
		private System.Nullable<long> _Phoneno;
		
		private string _MailID;
		
		private string _Stdaddress;
		
		private string _Bloodgrp;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _DeptID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRollnoChanging(int value);
    partial void OnRollnoChanged();
    partial void OnStdnameChanging(string value);
    partial void OnStdnameChanged();
    partial void OnPhonenoChanging(System.Nullable<long> value);
    partial void OnPhonenoChanged();
    partial void OnMailIDChanging(string value);
    partial void OnMailIDChanged();
    partial void OnStdaddressChanging(string value);
    partial void OnStdaddressChanged();
    partial void OnBloodgrpChanging(string value);
    partial void OnBloodgrpChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnDeptIDChanging(System.Nullable<int> value);
    partial void OnDeptIDChanged();
    #endregion
		
		public Clg_Dept()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rollno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Rollno
		{
			get
			{
				return this._Rollno;
			}
			set
			{
				if ((this._Rollno != value))
				{
					this.OnRollnoChanging(value);
					this.SendPropertyChanging();
					this._Rollno = value;
					this.SendPropertyChanged("Rollno");
					this.OnRollnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stdname", DbType="VarChar(30)")]
		public string Stdname
		{
			get
			{
				return this._Stdname;
			}
			set
			{
				if ((this._Stdname != value))
				{
					this.OnStdnameChanging(value);
					this.SendPropertyChanging();
					this._Stdname = value;
					this.SendPropertyChanged("Stdname");
					this.OnStdnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phoneno", DbType="BigInt")]
		public System.Nullable<long> Phoneno
		{
			get
			{
				return this._Phoneno;
			}
			set
			{
				if ((this._Phoneno != value))
				{
					this.OnPhonenoChanging(value);
					this.SendPropertyChanging();
					this._Phoneno = value;
					this.SendPropertyChanged("Phoneno");
					this.OnPhonenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailID", DbType="VarChar(40)")]
		public string MailID
		{
			get
			{
				return this._MailID;
			}
			set
			{
				if ((this._MailID != value))
				{
					this.OnMailIDChanging(value);
					this.SendPropertyChanging();
					this._MailID = value;
					this.SendPropertyChanged("MailID");
					this.OnMailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stdaddress", DbType="VarChar(40)")]
		public string Stdaddress
		{
			get
			{
				return this._Stdaddress;
			}
			set
			{
				if ((this._Stdaddress != value))
				{
					this.OnStdaddressChanging(value);
					this.SendPropertyChanging();
					this._Stdaddress = value;
					this.SendPropertyChanged("Stdaddress");
					this.OnStdaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloodgrp", DbType="VarChar(5)")]
		public string Bloodgrp
		{
			get
			{
				return this._Bloodgrp;
			}
			set
			{
				if ((this._Bloodgrp != value))
				{
					this.OnBloodgrpChanging(value);
					this.SendPropertyChanging();
					this._Bloodgrp = value;
					this.SendPropertyChanged("Bloodgrp");
					this.OnBloodgrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptID", DbType="Int")]
		public System.Nullable<int> DeptID
		{
			get
			{
				return this._DeptID;
			}
			set
			{
				if ((this._DeptID != value))
				{
					this.OnDeptIDChanging(value);
					this.SendPropertyChanging();
					this._DeptID = value;
					this.SendPropertyChanged("DeptID");
					this.OnDeptIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
