<?xml version="1.0" encoding="utf-8"?><Database Name="BANKING_SYSTEM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GL7RKG7\SQLEXPRESS;Initial Catalog=BANKING_SYSTEM;Integrated Security=True" SettingsObjectName="Bank.Properties.Settings" SettingsPropertyName="BANKING_SYSTEMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNTANT_DETAILS" Member="ACCOUNTANT_DETAILs">
    <Type Name="ACCOUNTANT_DETAIL">
      <Column Name="UserID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MailID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ACCOUNTANT_DETAIL_TRANSACTION_LOG" Member="TRANSACTION_LOGs" ThisKey="AccountNo" OtherKey="AccountNo" Type="TRANSACTION_LOG" />
      <Association Name="ACCOUNTANT_DETAIL_USER_TRANSACTION" Member="USER_TRANSACTIONs" ThisKey="AccountNo" OtherKey="AccountNo" Type="USER_TRANSACTION" />
      <Association Name="USER_REGISTRATION_ACCOUNTANT_DETAIL" Member="USER_REGISTRATION" ThisKey="UserID" OtherKey="UserID" Type="USER_REGISTRATION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANSACTION_LOG" Member="TRANSACTION_LOGs">
    <Type Name="TRANSACTION_LOG">
      <Column Name="TranID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="action" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="updatedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ACCOUNTANT_DETAIL_TRANSACTION_LOG" Member="ACCOUNTANT_DETAIL" ThisKey="AccountNo" OtherKey="AccountNo" Type="ACCOUNTANT_DETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.USER_REGISTRATION" Member="USER_REGISTRATIONs">
    <Type Name="USER_REGISTRATION">
      <Column Name="UserID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MailID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="USER_REGISTRATION_ACCOUNTANT_DETAIL" Member="ACCOUNTANT_DETAILs" ThisKey="UserID" OtherKey="UserID" Type="ACCOUNTANT_DETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.USER_TRANSACTION" Member="USER_TRANSACTIONs">
    <Type Name="USER_TRANSACTION">
      <Column Name="AccountNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="ACCOUNTANT_DETAIL_USER_TRANSACTION" Member="ACCOUNTANT_DETAIL" ThisKey="AccountNo" OtherKey="AccountNo" Type="ACCOUNTANT_DETAIL" IsForeignKey="true" />
    </Type>
  </Table>
</Database>